// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// 检测 localStorage 是否可用
const isLocalStorageAvailable = (): boolean => {
  try {
    const testKey = '__storage_test__';
    if (typeof window === 'undefined' || !window.localStorage) return false;
    window.localStorage.setItem(testKey, testKey);
    window.localStorage.removeItem(testKey);
    return true;
  } catch {
    return false;
  }
};

// 内存存储作为后备
const memoryStorage: Record<string, string> = {};

// 安全的 storage 包装器，处理某些浏览器（如隐私模式）的 localStorage 不可用问题
const safeStorage = {
  getItem: (key: string): string | null => {
    if (isLocalStorageAvailable()) {
      try {
        return localStorage.getItem(key);
      } catch {
        return memoryStorage[key] || null;
      }
    }
    return memoryStorage[key] || null;
  },
  setItem: (key: string, value: string): void => {
    if (isLocalStorageAvailable()) {
      try {
        localStorage.setItem(key, value);
        return;
      } catch {
        // 降级到内存存储
      }
    }
    memoryStorage[key] = value;
  },
  removeItem: (key: string): void => {
    if (isLocalStorageAvailable()) {
      try {
        localStorage.removeItem(key);
      } catch {
        // 忽略错误
      }
    }
    delete memoryStorage[key];
  },
};

let supabaseInstance: SupabaseClient<Database> | null = null;

try {
  if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
    supabaseInstance = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: safeStorage,
        persistSession: true,
        autoRefreshToken: true,
      }
    });
  } else {
    console.warn('Supabase credentials not found. Some features may not work.');
  }
} catch (error) {
  console.error('Failed to initialize Supabase client:', error);
}

// 创建一个 mock client 用于环境变量缺失的情况
const mockSupabase = {
  auth: {
    getSession: async () => ({ data: { session: null }, error: null }),
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
    signOut: async () => ({ error: null }),
    signInWithPassword: async () => ({ data: { user: null, session: null }, error: { message: 'Supabase not configured' } }),
    signUp: async () => ({ data: { user: null, session: null }, error: { message: 'Supabase not configured' } }),
  },
  from: () => ({
    select: () => ({ data: null, error: { message: 'Supabase not configured' } }),
    insert: () => ({ data: null, error: { message: 'Supabase not configured' } }),
    update: () => ({ data: null, error: { message: 'Supabase not configured' } }),
    delete: () => ({ data: null, error: { message: 'Supabase not configured' } }),
  }),
  functions: {
    invoke: async () => ({ data: null, error: { message: 'Supabase not configured' } }),
  },
} as unknown as SupabaseClient<Database>;

export const supabase = supabaseInstance || mockSupabase;
export { SUPABASE_URL };